all: \
  Output/Debug/Exe/01bsp_sctimer.elf\

-include Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.d
Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.o:../common/01bsp_sctimer/01bsp_sctimer.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.d -MQ Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/common/01bsp_sctimer/01bsp_sctimer.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.asm -o Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.asm

-include Output/Debug/Obj/01bsp_sctimer/adc.d
Output/Debug/Obj/01bsp_sctimer/adc.o:../../bsp/boards/nrf52840_dk/adc.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/adc.d -MQ Output/Debug/Obj/01bsp_sctimer/adc.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/adc.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/adc.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/adc.asm -o Output/Debug/Obj/01bsp_sctimer/adc.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/adc.asm

-include Output/Debug/Obj/01bsp_sctimer/board.d
Output/Debug/Obj/01bsp_sctimer/board.o:../../bsp/boards/nrf52840_dk/board.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/board.d -MQ Output/Debug/Obj/01bsp_sctimer/board.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/board.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/board.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/board.asm -o Output/Debug/Obj/01bsp_sctimer/board.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/board.asm

-include Output/Debug/Obj/01bsp_sctimer/cryptoengine.d
Output/Debug/Obj/01bsp_sctimer/cryptoengine.o:../../bsp/boards/nrf52840_dk/cryptoengine.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/cryptoengine.d -MQ Output/Debug/Obj/01bsp_sctimer/cryptoengine.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/cryptoengine.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/cryptoengine.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/cryptoengine.asm -o Output/Debug/Obj/01bsp_sctimer/cryptoengine.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/cryptoengine.asm

-include Output/Debug/Obj/01bsp_sctimer/debugpins.d
Output/Debug/Obj/01bsp_sctimer/debugpins.o:../../bsp/boards/nrf52840_dk/debugpins.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/debugpins.d -MQ Output/Debug/Obj/01bsp_sctimer/debugpins.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/debugpins.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/debugpins.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/debugpins.asm -o Output/Debug/Obj/01bsp_sctimer/debugpins.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/debugpins.asm

-include Output/Debug/Obj/01bsp_sctimer/eui64.d
Output/Debug/Obj/01bsp_sctimer/eui64.o:../../bsp/boards/nrf52840_dk/eui64.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/eui64.d -MQ Output/Debug/Obj/01bsp_sctimer/eui64.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/eui64.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/eui64.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/eui64.asm -o Output/Debug/Obj/01bsp_sctimer/eui64.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/eui64.asm

-include Output/Debug/Obj/01bsp_sctimer/i2c.d
Output/Debug/Obj/01bsp_sctimer/i2c.o:../../bsp/boards/nrf52840_dk/i2c.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/i2c.d -MQ Output/Debug/Obj/01bsp_sctimer/i2c.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/i2c.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/i2c.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/i2c.asm -o Output/Debug/Obj/01bsp_sctimer/i2c.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/i2c.asm

-include Output/Debug/Obj/01bsp_sctimer/leds.d
Output/Debug/Obj/01bsp_sctimer/leds.o:../../bsp/boards/nrf52840_dk/leds.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/leds.d -MQ Output/Debug/Obj/01bsp_sctimer/leds.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/leds.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/leds.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/leds.asm -o Output/Debug/Obj/01bsp_sctimer/leds.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/leds.asm

-include Output/Debug/Obj/01bsp_sctimer/radio.d
Output/Debug/Obj/01bsp_sctimer/radio.o:../../bsp/boards/nrf52840_dk/radio.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/radio.d -MQ Output/Debug/Obj/01bsp_sctimer/radio.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/radio.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/radio.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/radio.asm -o Output/Debug/Obj/01bsp_sctimer/radio.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/radio.asm

-include Output/Debug/Obj/01bsp_sctimer/sctimer.d
Output/Debug/Obj/01bsp_sctimer/sctimer.o:../../bsp/boards/nrf52840_dk/sctimer.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sctimer.d -MQ Output/Debug/Obj/01bsp_sctimer/sctimer.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sctimer.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sctimer.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sctimer.asm -o Output/Debug/Obj/01bsp_sctimer/sctimer.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sctimer.asm

-include Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.d
Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.o:../../bsp/boards/nrf52840_dk/sdk/ses_startup_nrf52840.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.d -MQ Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.o -quiet -lang-asm /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sdk/ses_startup_nrf52840.s -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840_PP.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840_PP.s -o Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.o -g -gdwarf-4
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840_PP.s

-include Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.d
Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.o:../../bsp/boards/nrf52840_dk/sdk/ses_startup_nrf_common.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.d -MQ Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.o -quiet -lang-asm /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sdk/ses_startup_nrf_common.s -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common_PP.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common_PP.s -o Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.o -g -gdwarf-4
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common_PP.s

-include Output/Debug/Obj/01bsp_sctimer/system_nrf52840.d
Output/Debug/Obj/01bsp_sctimer/system_nrf52840.o:../../bsp/boards/nrf52840_dk/sdk/system_nrf52840.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/system_nrf52840.d -MQ Output/Debug/Obj/01bsp_sctimer/system_nrf52840.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sdk/system_nrf52840.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/system_nrf52840.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/system_nrf52840.asm -o Output/Debug/Obj/01bsp_sctimer/system_nrf52840.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/system_nrf52840.asm

-include Output/Debug/Obj/01bsp_sctimer/thumb_crt0.d
Output/Debug/Obj/01bsp_sctimer/thumb_crt0.o:../../bsp/boards/nrf52840_dk/sdk/thumb_crt0.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/thumb_crt0.d -MQ Output/Debug/Obj/01bsp_sctimer/thumb_crt0.o -quiet -lang-asm /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sdk/thumb_crt0.s -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/thumb_crt0_PP.s
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/thumb_crt0_PP.s -o Output/Debug/Obj/01bsp_sctimer/thumb_crt0.o -g -gdwarf-4
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/thumb_crt0_PP.s

-include Output/Debug/Obj/01bsp_sctimer/sensors.d
Output/Debug/Obj/01bsp_sctimer/sensors.o:../../bsp/boards/nrf52840_dk/sensors.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sensors.d -MQ Output/Debug/Obj/01bsp_sctimer/sensors.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/sensors.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sensors.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sensors.asm -o Output/Debug/Obj/01bsp_sctimer/sensors.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/sensors.asm

-include Output/Debug/Obj/01bsp_sctimer/spi.d
Output/Debug/Obj/01bsp_sctimer/spi.o:../../bsp/boards/nrf52840_dk/spi.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/spi.d -MQ Output/Debug/Obj/01bsp_sctimer/spi.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/spi.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/spi.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/spi.asm -o Output/Debug/Obj/01bsp_sctimer/spi.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/spi.asm

-include Output/Debug/Obj/01bsp_sctimer/uart.d
Output/Debug/Obj/01bsp_sctimer/uart.o:../../bsp/boards/nrf52840_dk/uart.c
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/cc1" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc "-isystem/Applications/SEGGER Embedded Studio for ARM 6.30/include" -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/Users/lijingwei/Library/SEGGER/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/uart.d -MQ Output/Debug/Obj/01bsp_sctimer/uart.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/bsp/boards/nrf52840_dk/uart.c -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/uart.asm
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/as" --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/uart.asm -o Output/Debug/Obj/01bsp_sctimer/uart.o
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/rm" -f /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/uart.asm

Output/Debug/Exe/01bsp_sctimer.elf:\
  Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.o\
  Output/Debug/Obj/01bsp_sctimer/adc.o\
  Output/Debug/Obj/01bsp_sctimer/board.o\
  Output/Debug/Obj/01bsp_sctimer/cryptoengine.o\
  Output/Debug/Obj/01bsp_sctimer/debugpins.o\
  Output/Debug/Obj/01bsp_sctimer/eui64.o\
  Output/Debug/Obj/01bsp_sctimer/i2c.o\
  Output/Debug/Obj/01bsp_sctimer/leds.o\
  Output/Debug/Obj/01bsp_sctimer/radio.o\
  Output/Debug/Obj/01bsp_sctimer/sctimer.o\
  Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf52840.o\
  Output/Debug/Obj/01bsp_sctimer/ses_startup_nrf_common.o\
  Output/Debug/Obj/01bsp_sctimer/system_nrf52840.o\
  Output/Debug/Obj/01bsp_sctimer/thumb_crt0.o\
  Output/Debug/Obj/01bsp_sctimer/sensors.o\
  Output/Debug/Obj/01bsp_sctimer/spi.o\
  Output/Debug/Obj/01bsp_sctimer/uart.o\
  flash_placement.xml\
  /Users/lijingwei/Library/SEGGER/SEGGER\ Embedded\ Studio/v3/packages/libraries/libcxx/lib/libcxx_noexcept_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a
	"/Applications/SEGGER Embedded Studio for ARM 6.30/bin/mkld" -target arm -memory-map-segments "FLASH1 RX 0x0 0x100000;RAM1 RWX 0x20000000 0x40000" -section-placement-file flash_placement.xml -check-segment-overflow -symbols "__STACKSIZE__=8192;__STACKSIZE_PROCESS__=0;__HEAPSIZE__=8192" -section-placement-macros "FLASH_PH_START=0x0;FLASH_PH_SIZE=0x100000;RAM_PH_START=0x20000000;RAM_PH_SIZE=0x40000;FLASH_START=0x0;FLASH_SIZE=0x100000;RAM_START=0x20000000;RAM_SIZE=0x40000" /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.ld
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/ld" -X --omagic -eReset_Handler -EL --defsym=__SEGGER_RTL_vfprintf=__SEGGER_RTL_vfprintf_long --defsym=__SEGGER_RTL_vfscanf=__SEGGER_RTL_vfscanf_long --gc-sections -T/Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.ld -Map /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_sctimer.map -u_vectors -o /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_sctimer.elf --emit-relocs --start-group @/Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_sctimer/01bsp_sctimer.ind --end-group
	"/Applications/SEGGER Embedded Studio for ARM 6.30/gcc/arm-none-eabi/bin/objcopy" Output/Debug/Exe/01bsp_sctimer.elf /Users/lijingwei/Desktop/projects/iota5109/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_sctimer.hex -Oihex