all: \
  Output/Debug/Exe/01bsp_uart.elf\

-include Output/Debug/Obj/01bsp_uart/01bsp_uart.d
Output/Debug/Obj/01bsp_uart/01bsp_uart.o:../common/01bsp_uart/01bsp_uart.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.d -MQ Output/Debug/Obj/01bsp_uart/01bsp_uart.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/projects/common/01bsp_uart/01bsp_uart.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.asm -o Output/Debug/Obj/01bsp_uart/01bsp_uart.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.asm

-include Output/Debug/Obj/01bsp_uart/adc.d
Output/Debug/Obj/01bsp_uart/adc.o:../../bsp/boards/nrf52840_dk/adc.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/adc.d -MQ Output/Debug/Obj/01bsp_uart/adc.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/adc.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/adc.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/adc.asm -o Output/Debug/Obj/01bsp_uart/adc.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/adc.asm

-include Output/Debug/Obj/01bsp_uart/board.d
Output/Debug/Obj/01bsp_uart/board.o:../../bsp/boards/nrf52840_dk/board.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/board.d -MQ Output/Debug/Obj/01bsp_uart/board.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/board.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/board.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/board.asm -o Output/Debug/Obj/01bsp_uart/board.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/board.asm

-include Output/Debug/Obj/01bsp_uart/cryptoengine.d
Output/Debug/Obj/01bsp_uart/cryptoengine.o:../../bsp/boards/nrf52840_dk/cryptoengine.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/cryptoengine.d -MQ Output/Debug/Obj/01bsp_uart/cryptoengine.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/cryptoengine.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/cryptoengine.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/cryptoengine.asm -o Output/Debug/Obj/01bsp_uart/cryptoengine.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/cryptoengine.asm

-include Output/Debug/Obj/01bsp_uart/debugpins.d
Output/Debug/Obj/01bsp_uart/debugpins.o:../../bsp/boards/nrf52840_dk/debugpins.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/debugpins.d -MQ Output/Debug/Obj/01bsp_uart/debugpins.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/debugpins.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/debugpins.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/debugpins.asm -o Output/Debug/Obj/01bsp_uart/debugpins.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/debugpins.asm

-include Output/Debug/Obj/01bsp_uart/eui64.d
Output/Debug/Obj/01bsp_uart/eui64.o:../../bsp/boards/nrf52840_dk/eui64.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/eui64.d -MQ Output/Debug/Obj/01bsp_uart/eui64.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/eui64.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/eui64.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/eui64.asm -o Output/Debug/Obj/01bsp_uart/eui64.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/eui64.asm

-include Output/Debug/Obj/01bsp_uart/i2c.d
Output/Debug/Obj/01bsp_uart/i2c.o:../../bsp/boards/nrf52840_dk/i2c.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/i2c.d -MQ Output/Debug/Obj/01bsp_uart/i2c.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/i2c.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/i2c.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/i2c.asm -o Output/Debug/Obj/01bsp_uart/i2c.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/i2c.asm

-include Output/Debug/Obj/01bsp_uart/leds.d
Output/Debug/Obj/01bsp_uart/leds.o:../../bsp/boards/nrf52840_dk/leds.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/leds.d -MQ Output/Debug/Obj/01bsp_uart/leds.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/leds.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/leds.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/leds.asm -o Output/Debug/Obj/01bsp_uart/leds.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/leds.asm

-include Output/Debug/Obj/01bsp_uart/radio.d
Output/Debug/Obj/01bsp_uart/radio.o:../../bsp/boards/nrf52840_dk/radio.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/radio.d -MQ Output/Debug/Obj/01bsp_uart/radio.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/radio.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/radio.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/radio.asm -o Output/Debug/Obj/01bsp_uart/radio.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/radio.asm

-include Output/Debug/Obj/01bsp_uart/sctimer.d
Output/Debug/Obj/01bsp_uart/sctimer.o:../../bsp/boards/nrf52840_dk/sctimer.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sctimer.d -MQ Output/Debug/Obj/01bsp_uart/sctimer.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sctimer.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sctimer.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sctimer.asm -o Output/Debug/Obj/01bsp_uart/sctimer.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sctimer.asm

-include Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.d
Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.o:../../bsp/boards/nrf52840_dk/sdk/ses_startup_nrf52840.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.d -MQ Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.o -quiet -lang-asm /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sdk/ses_startup_nrf52840.s -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840_PP.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840_PP.s -o Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.o -g -gdwarf-4
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840_PP.s

-include Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.d
Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.o:../../bsp/boards/nrf52840_dk/sdk/ses_startup_nrf_common.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.d -MQ Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.o -quiet -lang-asm /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sdk/ses_startup_nrf_common.s -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common_PP.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common_PP.s -o Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.o -g -gdwarf-4
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common_PP.s

-include Output/Debug/Obj/01bsp_uart/system_nrf52840.d
Output/Debug/Obj/01bsp_uart/system_nrf52840.o:../../bsp/boards/nrf52840_dk/sdk/system_nrf52840.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/system_nrf52840.d -MQ Output/Debug/Obj/01bsp_uart/system_nrf52840.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sdk/system_nrf52840.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/system_nrf52840.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/system_nrf52840.asm -o Output/Debug/Obj/01bsp_uart/system_nrf52840.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/system_nrf52840.asm

-include Output/Debug/Obj/01bsp_uart/thumb_crt0.d
Output/Debug/Obj/01bsp_uart/thumb_crt0.o:../../bsp/boards/nrf52840_dk/sdk/thumb_crt0.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -E -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/thumb_crt0.d -MQ Output/Debug/Obj/01bsp_uart/thumb_crt0.o -quiet -lang-asm /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sdk/thumb_crt0.s -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/thumb_crt0_PP.s
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/thumb_crt0_PP.s -o Output/Debug/Obj/01bsp_uart/thumb_crt0.o -g -gdwarf-4
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/thumb_crt0_PP.s

-include Output/Debug/Obj/01bsp_uart/sensors.d
Output/Debug/Obj/01bsp_uart/sensors.o:../../bsp/boards/nrf52840_dk/sensors.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sensors.d -MQ Output/Debug/Obj/01bsp_uart/sensors.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/sensors.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sensors.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sensors.asm -o Output/Debug/Obj/01bsp_uart/sensors.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/sensors.asm

-include Output/Debug/Obj/01bsp_uart/spi.d
Output/Debug/Obj/01bsp_uart/spi.o:../../bsp/boards/nrf52840_dk/spi.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/spi.d -MQ Output/Debug/Obj/01bsp_uart/spi.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/spi.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/spi.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/spi.asm -o Output/Debug/Obj/01bsp_uart/spi.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/spi.asm

-include Output/Debug/Obj/01bsp_uart/uart.d
Output/Debug/Obj/01bsp_uart/uart.o:../../bsp/boards/nrf52840_dk/uart.c
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/cc1 -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -mcpu=cortex-m4 -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mtp=soft -mfp16-format=ieee -munaligned-access -nostdinc -isystem/usr/share/segger_embedded_studio_for_arm_6.30/include -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc "-I/root/.segger/SEGGER Embedded Studio/v3/packages/libraries/libcxx/include" -D__SIZEOF_WCHAR_T=4 -D__ARM_ARCH_7EM__ -D__SES_ARM -D__ARM_ARCH_FPV4_SP_D16__ -D__HEAP_SIZE__=8192 -D__SES_VERSION=63000 -D__GNU_LINKER -D_LIBCPP_HAS_NO_THREADS -D_LIBCPP_HAS_NO_OFF_T_FUNCTIONS -D__NO_AEABI_ERR__ -DDEBUG "-D DEBUG_NRF" -DNRF52840_XXAA -DNRF52840_DK -MD /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/uart.d -MQ Output/Debug/Obj/01bsp_uart/uart.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -fno-dwarf2-cfi-asm -ffunction-sections -fdata-sections -fshort-enums -fno-common /home/lijingwei/dev/openwsn-fw/bsp/boards/nrf52840_dk/uart.c -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/uart.asm
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/as --traditional-format -I../../bsp/boards -I../../bsp/boards/nrf52840_dk -I../../bsp/boards/nrf52840_dk/sdk -I../../inc -march=armv7e-m -mlittle-endian -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/uart.asm -o Output/Debug/Obj/01bsp_uart/uart.o
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/rm -f /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/uart.asm

Output/Debug/Exe/01bsp_uart.elf:\
  Output/Debug/Obj/01bsp_uart/01bsp_uart.o\
  Output/Debug/Obj/01bsp_uart/adc.o\
  Output/Debug/Obj/01bsp_uart/board.o\
  Output/Debug/Obj/01bsp_uart/cryptoengine.o\
  Output/Debug/Obj/01bsp_uart/debugpins.o\
  Output/Debug/Obj/01bsp_uart/eui64.o\
  Output/Debug/Obj/01bsp_uart/i2c.o\
  Output/Debug/Obj/01bsp_uart/leds.o\
  Output/Debug/Obj/01bsp_uart/radio.o\
  Output/Debug/Obj/01bsp_uart/sctimer.o\
  Output/Debug/Obj/01bsp_uart/ses_startup_nrf52840.o\
  Output/Debug/Obj/01bsp_uart/ses_startup_nrf_common.o\
  Output/Debug/Obj/01bsp_uart/system_nrf52840.o\
  Output/Debug/Obj/01bsp_uart/thumb_crt0.o\
  Output/Debug/Obj/01bsp_uart/sensors.o\
  Output/Debug/Obj/01bsp_uart/spi.o\
  Output/Debug/Obj/01bsp_uart/uart.o\
  flash_placement.xml\
  /root/.segger/SEGGER\ Embedded\ Studio/v3/packages/libraries/libcxx/lib/libcxx_noexcept_v7em_fpv4_sp_d16_hard_t_le_eabi_balanced.a
	/usr/share/segger_embedded_studio_for_arm_6.30/bin/mkld -target arm -memory-map-segments "FLASH1 RX 0x0 0x100000;RAM1 RWX 0x20000000 0x40000" -section-placement-file /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/flash_placement.xml -check-segment-overflow -symbols "__STACKSIZE__=8192;__STACKSIZE_PROCESS__=0;__HEAPSIZE__=8192" -section-placement-macros "FLASH_PH_START=0x0;FLASH_PH_SIZE=0x100000;RAM_PH_START=0x20000000;RAM_PH_SIZE=0x40000;FLASH_START=0x0;FLASH_SIZE=0x100000;RAM_START=0x20000000;RAM_SIZE=0x40000" /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.ld
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/ld -X --omagic -eReset_Handler -EL --defsym=__SEGGER_RTL_vfprintf=__SEGGER_RTL_vfprintf_long --defsym=__SEGGER_RTL_vfscanf=__SEGGER_RTL_vfscanf_long --gc-sections -T/home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.ld -Map /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_uart.map -u_vectors -o /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_uart.elf --emit-relocs --start-group @/home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Obj/01bsp_uart/01bsp_uart.ind --end-group
	/usr/share/segger_embedded_studio_for_arm_6.30/gcc/arm-none-eabi/bin/objcopy Output/Debug/Exe/01bsp_uart.elf /home/lijingwei/dev/openwsn-fw/projects/nrf52840_dk/Output/Debug/Exe/01bsp_uart.hex -Oihex